version: '3.8'

services:
  postgres:
    image: postgres:12
    environment:
      PGDATA: /var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./var/postgres/data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.10.20-management
    ports:
      - '15672:15672'
      - '5672:5672'
    restart: always
